[build]
  command = "npm run build && cd functions && npm i"
  publish="public"
  functions="functions"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
    from = "/r-*"
    to = "/.netlify/functions/redir"
    status = 200